"""
INEXION patient + physician report generation.

Two top-level functions:
- build_patient_report(...)   -> bytes (.docx)
- build_physician_report(...) -> bytes (.docx)

The Patient Report is a comprehensive INEXION-branded guidebook written in
patient-friendly language (~8th grade reading level). It explains every lab
value plainly and walks through biological / metabolic / liver / kidney age,
the normative reference percentile, and prioritized lifestyle recommendations.

The Physician Report is a clinical decision-support document at higher health
literacy. It surfaces biomarker contribution analysis (which markers most
accelerate or decelerate the patient's biological age across all four clocks)
and ranks intervention targets by predicted age delta improvement.

Numeric data (ages, deltas, percentiles, contribution magnitudes) is computed
deterministically from patient inputs; only the narrative interpretation is
generated by Claude, with a static fallback if the API call fails.
"""
from __future__ import annotations
import io
import json
import os
from datetime import datetime
from typing import Any

from docx import Document
from docx.shared import Inches, Pt, RGBColor, Cm
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_ALIGN_VERTICAL
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

# ---------------------------------------------------------------------------
# INEXION brand constants
# ---------------------------------------------------------------------------
NAVY_HEX  = "0D1B3E"
GOLD_HEX  = "C9941A"
LIGHT_HEX = "F2F4F8"
NAVY_RGB  = RGBColor(0x0D, 0x1B, 0x3E)
GOLD_RGB  = RGBColor(0xC9, 0x94, 0x1A)
GREY_RGB  = RGBColor(0x6B, 0x72, 0x80)
DARK_RGB  = RGBColor(0x1A, 0x1A, 0x2E)
WHITE_RGB = RGBColor(0xFF, 0xFF, 0xFF)


# ---------------------------------------------------------------------------
# Lab metadata - patient-friendly explanations used as static fallback
# when the Claude narrative call is unavailable. Keyed by the same names as
# the Patient Analysis page session state (without the "pa_" prefix).
# ---------------------------------------------------------------------------
LAB_METADATA: dict[str, dict[str, Any]] = {
    "albumin": {
        "label": "Albumin",
        "units": "g/dL",
        "ref_range": "3.5 - 5.5",
        "patient_text": (
            "Albumin is a protein made by your liver. It helps carry nutrients, "
            "hormones, and medicines through your body. Higher levels usually mean "
            "your liver is healthy and you have good nutrition."
        ),
    },
    "creatinine": {
        "label": "Creatinine",
        "units": "mg/dL",
        "ref_range": "0.6 - 1.3",
        "patient_text": (
            "Creatinine is a waste product made by your muscles. Your kidneys filter "
            "it out of your blood. Higher levels can mean your kidneys are working "
            "harder than they should."
        ),
    },
    "glucose": {
        "label": "Glucose (fasting)",
        "units": "mg/dL",
        "ref_range": "70 - 99",
        "patient_text": (
            "Glucose is sugar in your blood. After fasting overnight, healthy levels "
            "stay below 100. Higher values can be an early sign of insulin resistance "
            "or diabetes."
        ),
    },
    "bun": {
        "label": "BUN (Blood Urea Nitrogen)",
        "units": "mg/dL",
        "ref_range": "7 - 20",
        "patient_text": (
            "BUN measures another waste product your kidneys clear. Together with "
            "creatinine it gives a fuller picture of how well your kidneys are working."
        ),
    },
    "uric_acid": {
        "label": "Uric acid",
        "units": "mg/dL",
        "ref_range": "3.5 - 7.2",
        "patient_text": (
            "Uric acid is a byproduct of breaking down purines (found in red meat, "
            "alcohol, and some seafood). Higher levels can cause gout and may signal "
            "metabolic issues."
        ),
    },
    "crp": {
        "label": "CRP (C-reactive protein)",
        "units": "mg/L",
        "ref_range": "< 3.0",
        "patient_text": (
            "CRP measures inflammation in your body. Chronic inflammation is one of "
            "the strongest accelerators of biological aging - lower is better."
        ),
    },
    "lymph": {
        "label": "Lymphocyte percentage",
        "units": "%",
        "ref_range": "20 - 40",
        "patient_text": (
            "Lymphocytes are immune cells that fight off infections. The percentage "
            "of lymphocytes in your white blood cells tells us about your immune "
            "system's health."
        ),
    },
    "wbc": {
        "label": "WBC (white blood cell count)",
        "units": "x1000/uL",
        "ref_range": "4.5 - 11.0",
        "patient_text": (
            "White blood cells fight infection. Levels that are too high or too low "
            "can both be concerning."
        ),
    },
    "mcv": {
        "label": "MCV (mean corpuscular volume)",
        "units": "fL",
        "ref_range": "80 - 100",
        "patient_text": (
            "MCV measures the average size of your red blood cells. Larger or smaller "
            "than normal can point to nutritional deficiencies or other issues."
        ),
    },
    "rdw": {
        "label": "RDW (red cell distribution width)",
        "units": "%",
        "ref_range": "11.5 - 14.5",
        "patient_text": (
            "RDW shows how much your red blood cells vary in size. Higher values are "
            "linked to faster aging and higher long-term risk."
        ),
    },
    "hba1c": {
        "label": "HbA1c",
        "units": "%",
        "ref_range": "< 5.7",
        "patient_text": (
            "HbA1c shows your average blood sugar over the past 2-3 months. It's the "
            "best single number for tracking your blood sugar control."
        ),
    },
    "total_chol": {
        "label": "Total cholesterol",
        "units": "mg/dL",
        "ref_range": "< 200",
        "patient_text": (
            "Total cholesterol is the sum of all cholesterol types in your blood. "
            "Lower values reduce heart disease risk - but the breakdown into HDL "
            "and LDL matters more."
        ),
    },
    "hdl": {
        "label": "HDL cholesterol",
        "units": "mg/dL",
        "ref_range": "> 40 (M), > 50 (F)",
        "patient_text": (
            "HDL is the 'good' cholesterol. It helps remove cholesterol buildup from "
            "your arteries. Higher is better."
        ),
    },
    "tbili": {
        "label": "Total bilirubin",
        "units": "mg/dL",
        "ref_range": "0.1 - 1.2",
        "patient_text": (
            "Bilirubin is a waste product your liver clears. Mildly higher levels "
            "can sometimes be protective; very high levels can signal liver issues."
        ),
    },
    "total_protein": {
        "label": "Total protein",
        "units": "g/dL",
        "ref_range": "6.0 - 8.3",
        "patient_text": (
            "Total protein measures all the proteins (including albumin) in your "
            "blood. Reflects nutrition status and liver / kidney function."
        ),
    },
    "alkphos": {
        "label": "Alkaline phosphatase",
        "units": "U/L",
        "ref_range": "40 - 130",
        "patient_text": (
            "An enzyme found in liver and bone. Elevated levels can signal liver, "
            "bone, or bile-duct problems."
        ),
    },
    "platelet": {
        "label": "Platelet count",
        "units": "x1000/uL",
        "ref_range": "150 - 400",
        "patient_text": (
            "Platelets help your blood clot when you cut yourself. Low or high "
            "counts can both have meaning."
        ),
    },
    "ldh": {
        "label": "LDH (lactate dehydrogenase)",
        "units": "U/L",
        "ref_range": "140 - 280",
        "patient_text": (
            "LDH is released when cells are damaged. Higher levels can be a "
            "non-specific marker of cellular stress."
        ),
    },
    "sbp": {
        "label": "Systolic blood pressure",
        "units": "mmHg",
        "ref_range": "< 120",
        "patient_text": (
            "Systolic is the top number in a blood pressure reading - the pressure "
            "when your heart beats. Lower is generally better."
        ),
    },
    "dbp": {
        "label": "Diastolic blood pressure",
        "units": "mmHg",
        "ref_range": "< 80",
        "patient_text": (
            "Diastolic is the bottom number - the pressure when your heart is at "
            "rest between beats."
        ),
    },
}


# ---------------------------------------------------------------------------
# docx low-level helpers
# ---------------------------------------------------------------------------
def _shade_cell(cell, hex_color: str) -> None:
    """Apply solid fill shading to a docx table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def _set_cell_borders(cell, color: str = "0D1B3E", size: str = "4") -> None:
    """Add visible borders on all four sides of a table cell."""
    tcPr = cell._tc.get_or_add_tcPr()
    tcBorders = OxmlElement("w:tcBorders")
    for edge in ("top", "left", "bottom", "right"):
        b = OxmlElement(f"w:{edge}")
        b.set(qn("w:val"), "single")
        b.set(qn("w:sz"), size)
        b.set(qn("w:color"), color)
        tcBorders.append(b)
    tcPr.append(tcBorders)


def _add_hr(doc, color: str = GOLD_HEX) -> None:
    """Add a thin horizontal rule using a 1-row, 1-col borderless table."""
    p = doc.add_paragraph()
    pPr = p._p.get_or_add_pPr()
    pBdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "8")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), color)
    pBdr.append(bottom)
    pPr.append(pBdr)


def _write_h1(doc, text: str, color=NAVY_RGB) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.bold = True
    run.font.size = Pt(18)
    run.font.color.rgb = color
    run.font.name = "Calibri"


def _write_h2(doc, text: str, color=NAVY_RGB) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text.upper())
    run.bold = True
    run.font.size = Pt(12)
    run.font.color.rgb = color
    run.font.name = "Calibri"
    pf = p.paragraph_format
    pf.space_before = Pt(14)
    pf.space_after = Pt(4)


def _write_p(doc, text: str, size: int = 11, color=DARK_RGB,
             bold: bool = False, italic: bool = False) -> None:
    p = doc.add_paragraph()
    run = p.add_run(text)
    run.font.size = Pt(size)
    run.font.color.rgb = color
    run.bold = bold
    run.italic = italic
    run.font.name = "Calibri"


def _write_kv(doc, key: str, value: str) -> None:
    """Write a 'Label: Value' line with bold label."""
    p = doc.add_paragraph()
    r1 = p.add_run(f"{key}: ")
    r1.bold = True
    r1.font.size = Pt(11)
    r1.font.color.rgb = NAVY_RGB
    r2 = p.add_run(value)
    r2.font.size = Pt(11)
    r2.font.color.rgb = DARK_RGB


# ---------------------------------------------------------------------------
# Cover page builder
# ---------------------------------------------------------------------------
def _build_cover(doc, logo_path: str | None, report_label: str,
                 patient_age: int, patient_sex: str,
                 patient_race: str = "") -> None:
    """Cover with INEXION logo (preserved aspect ratio), navy title bar, date."""
    if logo_path and os.path.exists(logo_path):
        p = doc.add_paragraph()
        p.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = p.add_run()
        run.add_picture(logo_path, width=Inches(2.6))

    # Navy title bar with INEXION wordmark
    table = doc.add_table(rows=1, cols=1)
    table.alignment = WD_ALIGN_PARAGRAPH.CENTER
    cell = table.cell(0, 0)
    _shade_cell(cell, NAVY_HEX)
    cell.width = Inches(6.5)

    p1 = cell.paragraphs[0]
    p1.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r1 = p1.add_run("INEXION LONGEVITY REGISTRY")
    r1.bold = True
    r1.font.size = Pt(11)
    r1.font.color.rgb = GOLD_RGB
    r1.font.name = "Calibri"

    p2 = cell.add_paragraph()
    p2.alignment = WD_ALIGN_PARAGRAPH.CENTER
    r2 = p2.add_run(report_label)
    r2.bold = True
    r2.font.size = Pt(22)
    r2.font.color.rgb = WHITE_RGB
    r2.font.name = "Calibri"

    p3 = cell.add_paragraph()
    p3.alignment = WD_ALIGN_PARAGRAPH.CENTER
    today = datetime.now().strftime("%B %d, %Y")
    demo_bits = [f"Age {patient_age}", patient_sex]
    if patient_race:
        demo_bits.append(patient_race)
    r3 = p3.add_run(f"{' | '.join(demo_bits)}  ·  {today}")
    r3.font.size = Pt(10)
    r3.font.color.rgb = WHITE_RGB
    r3.font.name = "Calibri"

    doc.add_paragraph()  # spacer
    _add_hr(doc, GOLD_HEX)


# ---------------------------------------------------------------------------
# Claude narrative generation
# ---------------------------------------------------------------------------
def _claude_call(system: str, user: str, max_tokens: int = 2200) -> dict | None:
    """Single Haiku call expecting a JSON object back. Returns None on failure."""
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        return None
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=api_key)
        resp = client.messages.create(
            model="claude-haiku-4-5-20251001",
            max_tokens=max_tokens,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
        raw = resp.content[0].text.strip()
        if raw.startswith("```"):
            raw = "\n".join(raw.split("\n")[1:])
        if raw.endswith("```"):
            raw = "\n".join(raw.split("\n")[:-1])
        return json.loads(raw)
    except Exception:
        return None


def _generate_patient_narrative(ctx: dict) -> dict:
    system = (
        "You are a longevity clinic patient educator at INEXION, a longevity-focused "
        "medical practice. Write in clear, encouraging, patient-friendly language at "
        "approximately an 8th-grade reading level. Be honest about findings without "
        "being alarming. Avoid jargon; when you must use a medical term, briefly "
        "explain it. Always return strictly valid JSON with no markdown fences."
    )
    user = (
        "Generate patient-facing report content for a longevity clinic visit. "
        "Patient context (JSON):\n"
        f"{json.dumps(ctx, indent=2, default=str)}\n\n"
        "Return a JSON object with these exact keys:\n"
        "{\n"
        '  "executive_summary": "2-3 plain-language sentences summarizing where the '
        'patient stands biologically vs their chronological age",\n'
        '  "biological_age_narrative": "3-4 short paragraphs explaining biological '
        'age vs chronological age, what the patient\'s delta means for their '
        'healthspan, and how to interpret the population percentile",\n'
        '  "organ_ages_narrative": "2-3 short paragraphs comparing the patient\'s '
        'metabolic, liver, and kidney ages and what each tells them",\n'
        '  "intervention_summary": "1-2 paragraphs explaining how lifestyle changes '
        'can move biological age in their favor, written hopefully and concretely",\n'
        '  "recommendations": ["5 to 7 specific actionable lifestyle / health '
        "recommendations ordered by likely impact, each one a single complete "
        'sentence the patient can act on this month"]\n'
        "}\n"
        "Do NOT include markdown fences, just the JSON."
    )
    return _claude_call(system, user, max_tokens=2400) or {}


def _generate_physician_narrative(ctx: dict) -> dict:
    system = (
        "You are a clinical decision-support assistant for longevity-medicine "
        "clinicians at INEXION. Write at a clinician-appropriate health-literacy "
        "level: precise, quantitative, action-oriented. Cite contribution magnitudes "
        "by name. Prioritize interventions with the highest predicted age-delta "
        "improvement. Always return strictly valid JSON with no markdown fences."
    )
    user = (
        "Generate clinical decision-support content for a longevity clinic patient "
        "visit. Patient + biomarker contribution context (JSON):\n"
        f"{json.dumps(ctx, indent=2, default=str)}\n\n"
        "Return a JSON object with these exact keys:\n"
        "{\n"
        '  "executive_summary": "2-3 sentence clinical summary including PhenoAge, '
        'delta vs chronological, and the single highest-magnitude age accelerator",\n'
        '  "biomarker_analysis": "2-3 paragraphs identifying which biomarkers most '
        'strongly accelerate AND decelerate this patient\'s biological age across '
        'all four clocks. Be quantitative - cite specific contribution magnitudes",\n'
        '  "intervention_targets": [\n'
        '     {"target": "<specific biomarker target value>", '
        '"rationale": "<why this is the priority>", '
        '"approach": "<concrete clinical approach: lifestyle, supplement, '
        'pharmacologic options as appropriate>"}\n'
        "  ],\n"
        '  "follow_up": "2-3 sentences on repeat testing cadence and any specialist '
        'referrals worth considering"\n'
        "}\n"
        "Provide 4-6 intervention_targets ranked by predicted impact. Do NOT include "
        "markdown fences, just the JSON."
    )
    return _claude_call(system, user, max_tokens=2400) or {}


# ---------------------------------------------------------------------------
# PATIENT REPORT
# ---------------------------------------------------------------------------
def build_patient_report(
    *,
    patient: dict,
    labs: dict,
    phenoage: dict,
    organ_ages: dict,
    contributions: dict,
    percentile: int | None = None,
    logo_path: str | None = None,
) -> bytes:
    """
    Build the comprehensive patient guidebook .docx.

    Args:
        patient: {age, sex, race, height_in, weight_lb, bmi, waist_in}
        labs: {biomarker_key: float}  - 20 lab values
        phenoage: {phenoage, delta, mortality_10y}
        organ_ages: {metabolic_age, metabolic_delta, liver_age, liver_delta,
                     kidney_age, kidney_delta}
        contributions: {clock_name: {marker_label: float}} - per-clock waterfall
        percentile: 0-100 vs matched cohort, optional
        logo_path: path to inexion_logo.png

    Returns:
        bytes of the .docx file
    """
    ctx = {"patient": patient, "labs": labs, "phenoage": phenoage,
           "organ_ages": organ_ages, "contributions": contributions,
           "percentile": percentile}
    narrative = _generate_patient_narrative(ctx)

    doc = Document()

    # Page margins
    for section in doc.sections:
        section.top_margin    = Cm(1.8)
        section.bottom_margin = Cm(1.8)
        section.left_margin   = Cm(2.0)
        section.right_margin  = Cm(2.0)

    _build_cover(doc, logo_path, "Patient Report",
                 patient_age=patient.get("age", 0),
                 patient_sex=patient.get("sex", ""),
                 patient_race=patient.get("race", ""))

    # ----- Executive summary -----
    _write_h1(doc, "Your Results at a Glance")
    exec_summary = narrative.get("executive_summary") or _patient_static_summary(
        phenoage, organ_ages)
    _write_p(doc, exec_summary, size=12)

    # Snapshot table - chronological vs PhenoAge vs each organ age
    _write_h2(doc, "Your Ages — Chronological vs Biological")
    snap = doc.add_table(rows=5, cols=3)
    snap.alignment = WD_ALIGN_PARAGRAPH.CENTER
    headers = ["Measurement", "Your value", "What it means"]
    for j, h in enumerate(headers):
        c = snap.cell(0, j)
        _shade_cell(c, NAVY_HEX)
        _set_cell_borders(c)
        run = c.paragraphs[0].add_run(h)
        run.bold = True
        run.font.color.rgb = WHITE_RGB
        run.font.size = Pt(10)
    rows = [
        ("Chronological age", f"{patient.get('age', 0)} years",
         "Your age in calendar years."),
        ("Biological age (PhenoAge)",
         f"{phenoage.get('phenoage', 0):.1f} years",
         _delta_phrase(phenoage.get("delta", 0))),
        ("Metabolic age",
         f"{organ_ages.get('metabolic_age', 0):.1f} years"
         if organ_ages.get("metabolic_age") is not None else "Not available",
         _delta_phrase(organ_ages.get("metabolic_delta", 0))),
        ("Liver age",
         f"{organ_ages.get('liver_age', 0):.1f} years"
         if organ_ages.get("liver_age") is not None else "Not available",
         _delta_phrase(organ_ages.get("liver_delta", 0))),
        ("Kidney age",
         f"{organ_ages.get('kidney_age', 0):.1f} years"
         if organ_ages.get("kidney_age") is not None else "Not available",
         _delta_phrase(organ_ages.get("kidney_delta", 0))),
    ]
    for i, (a, b, c) in enumerate(rows, start=1):
        for j, val in enumerate((a, b, c)):
            cell = snap.cell(i, j)
            _set_cell_borders(cell, color="C7CCDB", size="2")
            _shade_cell(cell, LIGHT_HEX if i % 2 == 0 else "FFFFFF")
            r = cell.paragraphs[0].add_run(val)
            r.font.size = Pt(10)
            r.font.color.rgb = DARK_RGB
            if j == 0:
                r.bold = True

    if phenoage.get("mortality_10y") is not None:
        _write_p(
            doc,
            f"Estimated 10-year all-cause mortality risk: "
            f"{phenoage.get('mortality_10y', 0)*100:.1f}% (modeled from PhenoAge).",
            size=10, color=GREY_RGB, italic=True,
        )

    if percentile is not None:
        _write_p(
            doc,
            f"Population percentile: you sit at the {percentile}th percentile "
            f"vs a matched-cohort reference (same age, sex, and ancestry). "
            f"A lower percentile is better.",
            size=11,
        )

    doc.add_paragraph()

    # ----- Biological age narrative -----
    _write_h1(doc, "Understanding Your Biological Age")
    bio_text = narrative.get("biological_age_narrative") or _patient_static_bio(
        patient, phenoage, percentile)
    for para in [p.strip() for p in bio_text.split("\n\n") if p.strip()]:
        _write_p(doc, para, size=11)

    # ----- Organ ages narrative -----
    _write_h1(doc, "Your Organ Ages")
    organ_text = narrative.get("organ_ages_narrative") or _patient_static_organs(
        organ_ages)
    for para in [p.strip() for p in organ_text.split("\n\n") if p.strip()]:
        _write_p(doc, para, size=11)

    # ----- Lab explanations -----
    _write_h1(doc, "Your Lab Results Explained")
    _write_p(
        doc,
        "Each lab below shows your value, the typical healthy range, and a plain "
        "explanation of what the test measures. Values flagged below or above the "
        "range deserve a closer look with your clinician.",
        size=11,
    )

    lab_table = doc.add_table(rows=1, cols=4)
    lab_table.alignment = WD_ALIGN_PARAGRAPH.CENTER
    for j, h in enumerate(["Test", "Your value", "Typical range", "What it means"]):
        c = lab_table.cell(0, j)
        _shade_cell(c, NAVY_HEX)
        _set_cell_borders(c)
        run = c.paragraphs[0].add_run(h)
        run.bold = True
        run.font.color.rgb = WHITE_RGB
        run.font.size = Pt(10)

    for key, meta in LAB_METADATA.items():
        val = labs.get(key)
        if val is None:
            continue
        row = lab_table.add_row()
        for j, txt in enumerate([
            meta["label"],
            f"{val:.2f} {meta['units']}" if isinstance(val, (int, float))
            else str(val),
            meta["ref_range"],
            meta["patient_text"],
        ]):
            cell = row.cells[j]
            _set_cell_borders(cell, color="C7CCDB", size="2")
            r = cell.paragraphs[0].add_run(txt)
            r.font.size = Pt(9)
            r.font.color.rgb = DARK_RGB
            if j == 0:
                r.bold = True

    # ----- What you can do -----
    doc.add_page_break()
    _write_h1(doc, "What You Can Do This Month")
    int_summary = narrative.get("intervention_summary")
    if int_summary:
        _write_p(doc, int_summary, size=11)

    recs = narrative.get("recommendations") or _patient_static_recs(contributions)
    for i, rec in enumerate(recs, start=1):
        p = doc.add_paragraph()
        r1 = p.add_run(f"{i}.  ")
        r1.bold = True
        r1.font.color.rgb = GOLD_RGB
        r1.font.size = Pt(11)
        r2 = p.add_run(rec)
        r2.font.size = Pt(11)
        r2.font.color.rgb = DARK_RGB

    # ----- Disclaimer -----
    doc.add_paragraph()
    _add_hr(doc, GOLD_HEX)
    _write_p(
        doc,
        "This report is for educational purposes only and does not replace medical "
        "advice from a licensed clinician. Biological-age estimates are population "
        "models with confidence intervals; results may shift modestly between visits. "
        "Discuss any changes to medication, supplementation, or activity with your "
        "INEXION clinician before acting on these recommendations.",
        size=9, color=GREY_RGB, italic=True,
    )

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


# ---------------------------------------------------------------------------
# PHYSICIAN REPORT
# ---------------------------------------------------------------------------
def build_physician_report(
    *,
    patient: dict,
    labs: dict,
    phenoage: dict,
    organ_ages: dict,
    contributions: dict,
    percentile: int | None = None,
    logo_path: str | None = None,
) -> bytes:
    """Build the clinical decision-support .docx (higher-literacy report)."""
    ctx = {"patient": patient, "labs": labs, "phenoage": phenoage,
           "organ_ages": organ_ages, "contributions": contributions,
           "percentile": percentile}
    narrative = _generate_physician_narrative(ctx)

    doc = Document()
    for section in doc.sections:
        section.top_margin    = Cm(1.8)
        section.bottom_margin = Cm(1.8)
        section.left_margin   = Cm(2.0)
        section.right_margin  = Cm(2.0)

    _build_cover(doc, logo_path, "Physician Report",
                 patient_age=patient.get("age", 0),
                 patient_sex=patient.get("sex", ""),
                 patient_race=patient.get("race", ""))

    # ----- Executive summary -----
    _write_h1(doc, "Executive Summary")
    summary = narrative.get("executive_summary") or _physician_static_summary(
        phenoage, organ_ages, contributions)
    _write_p(doc, summary, size=11)

    # Vitals + biological age table
    _write_h2(doc, "Biological Age Profile")
    chrono = patient.get("age", 0)
    rows = [
        ("Chronological age (yr)", f"{chrono}"),
        ("PhenoAge (yr)",
         f"{phenoage.get('phenoage', 0):.2f}  (Δ {phenoage.get('delta', 0):+.2f})"),
        ("10-yr mortality risk",
         f"{phenoage.get('mortality_10y', 0)*100:.2f}%"
         if phenoage.get("mortality_10y") is not None else "—"),
        ("Population percentile",
         f"{percentile}th  (matched age × sex × race)"
         if percentile is not None else "—"),
        ("Metabolic age (yr)",
         f"{organ_ages.get('metabolic_age', 0):.2f}  "
         f"(Δ {organ_ages.get('metabolic_delta', 0):+.2f})"
         if organ_ages.get("metabolic_age") is not None else "—"),
        ("Liver age (yr)",
         f"{organ_ages.get('liver_age', 0):.2f}  "
         f"(Δ {organ_ages.get('liver_delta', 0):+.2f})"
         if organ_ages.get("liver_age") is not None else "—"),
        ("Kidney age (yr)",
         f"{organ_ages.get('kidney_age', 0):.2f}  "
         f"(Δ {organ_ages.get('kidney_delta', 0):+.2f})"
         if organ_ages.get("kidney_age") is not None else "—"),
    ]
    _two_col_table(doc, rows)

    # ----- Biomarker contribution analysis -----
    _write_h1(doc, "Biomarker Contribution Analysis")
    bio_text = narrative.get("biomarker_analysis") or _physician_static_bio(
        contributions)
    for para in [p.strip() for p in bio_text.split("\n\n") if p.strip()]:
        _write_p(doc, para, size=11)

    # Per-clock contribution tables (sorted by absolute magnitude)
    for clock_name, clock_contrib in (contributions or {}).items():
        if not clock_contrib:
            continue
        _write_h2(doc, f"{clock_name} contributions")
        ranked = sorted(clock_contrib.items(),
                         key=lambda kv: abs(kv[1] or 0), reverse=True)
        tbl = doc.add_table(rows=1, cols=3)
        for j, h in enumerate(["Marker", "Δ years", "Direction"]):
            c = tbl.cell(0, j)
            _shade_cell(c, NAVY_HEX)
            _set_cell_borders(c)
            run = c.paragraphs[0].add_run(h)
            run.bold = True
            run.font.color.rgb = WHITE_RGB
            run.font.size = Pt(10)
        for marker, contrib in ranked:
            row = tbl.add_row()
            cells = row.cells
            _set_cell_borders(cells[0], color="C7CCDB", size="2")
            _set_cell_borders(cells[1], color="C7CCDB", size="2")
            _set_cell_borders(cells[2], color="C7CCDB", size="2")
            cells[0].paragraphs[0].add_run(marker).font.size = Pt(10)
            cells[1].paragraphs[0].add_run(f"{contrib:+.2f}").font.size = Pt(10)
            direction = "Accelerator" if contrib > 0 else "Decelerator" if contrib < 0 else "Neutral"
            cells[2].paragraphs[0].add_run(direction).font.size = Pt(10)

    # ----- Intervention targets -----
    doc.add_page_break()
    _write_h1(doc, "Intervention Targets (ranked by predicted Δ-age impact)")
    targets = narrative.get("intervention_targets") or \
              _physician_static_targets(contributions)
    for i, t in enumerate(targets, start=1):
        if isinstance(t, str):
            target, rationale, approach = t, "", ""
        else:
            target = t.get("target", "")
            rationale = t.get("rationale", "")
            approach = t.get("approach", "")
        p = doc.add_paragraph()
        r1 = p.add_run(f"{i}.  {target}")
        r1.bold = True
        r1.font.color.rgb = NAVY_RGB
        r1.font.size = Pt(11)
        if rationale:
            _write_p(doc, f"Rationale: {rationale}", size=10,
                      color=GREY_RGB, italic=True)
        if approach:
            _write_p(doc, f"Approach: {approach}", size=10)

    # ----- Follow-up -----
    follow = narrative.get("follow_up")
    if follow:
        _write_h1(doc, "Follow-Up")
        _write_p(doc, follow, size=11)

    # ----- Lab reference table -----
    doc.add_page_break()
    _write_h1(doc, "Lab Values - Reference Table")
    lab_tbl = doc.add_table(rows=1, cols=4)
    for j, h in enumerate(["Marker", "Value", "Units", "Typical range"]):
        c = lab_tbl.cell(0, j)
        _shade_cell(c, NAVY_HEX)
        _set_cell_borders(c)
        run = c.paragraphs[0].add_run(h)
        run.bold = True
        run.font.color.rgb = WHITE_RGB
        run.font.size = Pt(10)
    for key, meta in LAB_METADATA.items():
        val = labs.get(key)
        if val is None:
            continue
        row = lab_tbl.add_row()
        cells = row.cells
        for j, txt in enumerate([meta["label"], f"{val:.2f}",
                                  meta["units"], meta["ref_range"]]):
            _set_cell_borders(cells[j], color="C7CCDB", size="2")
            r = cells[j].paragraphs[0].add_run(txt)
            r.font.size = Pt(9)
            r.font.color.rgb = DARK_RGB

    doc.add_paragraph()
    _add_hr(doc, GOLD_HEX)
    _write_p(
        doc,
        "Generated by the INEXION Longevity Registry. Models: PhenoAge "
        "(Levine 2018), organ-clocks fit on NHANES + MIDUS within-cohort "
        "regression. Δ-age values are statistical estimates with measurement "
        "error; bootstrap CIs available in the Patient Analysis app.",
        size=9, color=GREY_RGB, italic=True,
    )

    buf = io.BytesIO()
    doc.save(buf)
    buf.seek(0)
    return buf.read()


# ---------------------------------------------------------------------------
# Static fallback narrative (used when ANTHROPIC_API_KEY is missing or call fails)
# ---------------------------------------------------------------------------
def _delta_phrase(delta: float) -> str:
    if delta is None:
        return "—"
    if delta < -1.0:
        return f"{abs(delta):.1f} years younger biologically"
    if delta > 1.0:
        return f"{abs(delta):.1f} years older biologically"
    return "essentially aligned with chronological age"


def _patient_static_summary(phenoage: dict, organ_ages: dict) -> str:
    delta = phenoage.get("delta", 0)
    if delta < -2:
        bottom = ("Your biological-age results are encouraging — your body is "
                  "tracking younger than your calendar age.")
    elif delta > 2:
        bottom = ("Your biological-age results suggest your body is aging "
                  "faster than your calendar age — there's real opportunity "
                  "to slow this down.")
    else:
        bottom = ("Your biological-age results sit close to your calendar age. "
                  "Targeted lifestyle changes can move them in your favor.")
    return (
        f"Your PhenoAge is {phenoage.get('phenoage', 0):.1f} years compared to a "
        f"chronological age that's {_delta_phrase(delta)}. {bottom}"
    )


def _patient_static_bio(patient: dict, phenoage: dict,
                          percentile: int | None) -> str:
    delta = phenoage.get("delta", 0)
    pct = f"You sit at the {percentile}th percentile of a matched comparison " \
           f"group (same age, sex, and ancestry). Lower percentiles are " \
           f"better — they mean fewer people in your matched group are aging " \
           f"as well as you are." if percentile is not None else ""
    return (
        "Biological age uses your blood markers to estimate how well your "
        "body is functioning. It can run faster or slower than your calendar "
        "age depending on inflammation, metabolism, organ stress, and "
        "lifestyle factors.\n\n"
        f"Your PhenoAge of {phenoage.get('phenoage', 0):.1f} years versus a "
        f"chronological age of {patient.get('age', 0)} years means you're "
        f"{_delta_phrase(delta)}. The single biggest reason biological age "
        "shifts is chronic inflammation and metabolic strain, which tend to "
        "respond well to diet, exercise, sleep, and stress management.\n\n"
        f"{pct}"
    )


def _patient_static_organs(organ_ages: dict) -> str:
    bits = []
    for label, k_age, k_d in [("metabolic", "metabolic_age", "metabolic_delta"),
                                ("liver",     "liver_age",     "liver_delta"),
                                ("kidney",    "kidney_age",    "kidney_delta")]:
        a = organ_ages.get(k_age)
        d = organ_ages.get(k_d, 0)
        if a is None:
            continue
        bits.append(
            f"Your {label} age is {a:.1f} years — "
            f"{_delta_phrase(d)} on this organ system."
        )
    if not bits:
        return ("Organ age estimates were not available for this report. "
                "Talk with your clinician about which organ-specific "
                "biomarkers might be worth tracking.")
    return " ".join(bits)


def _patient_static_recs(contributions: dict) -> list[str]:
    return [
        "Aim for 150 minutes of moderate-intensity exercise per week plus 2 "
        "strength-training sessions — exercise is the single most consistent "
        "biological-age decelerator across studies.",
        "Anchor meals around protein, fiber, and colorful plants; minimize "
        "ultra-processed foods, which drive inflammation and accelerate aging.",
        "Protect 7-9 hours of sleep on a consistent schedule; sleep debt "
        "directly elevates inflammatory markers and accelerates biological age.",
        "If you drink alcohol, hold it to 3 drinks per week or less — alcohol "
        "is a major driver of liver-age acceleration in registry data.",
        "Schedule a follow-up lab panel in 3-4 months to see how these changes "
        "are reflected in your biomarkers.",
    ]


def _physician_static_summary(phenoage: dict, organ_ages: dict,
                                contributions: dict) -> str:
    delta = phenoage.get("delta", 0)
    pheno = contributions.get("PhenoAge", {})
    if pheno:
        top = max(pheno.items(), key=lambda kv: abs(kv[1] or 0))
        top_str = f" Top accelerator: {top[0]} ({top[1]:+.2f} yr)."
    else:
        top_str = ""
    return (
        f"PhenoAge {phenoage.get('phenoage', 0):.2f} yr "
        f"(Δ {delta:+.2f} vs chronological); "
        f"10y mortality {phenoage.get('mortality_10y', 0)*100:.2f}%."
        f"{top_str}"
    )


def _physician_static_bio(contributions: dict) -> str:
    lines = []
    for clock, contrib in (contributions or {}).items():
        if not contrib:
            continue
        ranked = sorted(contrib.items(), key=lambda kv: abs(kv[1] or 0), reverse=True)
        top3 = ranked[:3]
        bits = ", ".join(f"{m} ({v:+.2f})" for m, v in top3)
        lines.append(f"{clock}: {bits}.")
    if not lines:
        return ("Per-clock contribution data was not available; refer to the "
                "Patient Analysis app for detailed waterfall plots.")
    return "Top contributors by absolute magnitude across each clock:\n\n" + \
           "\n\n".join(lines)


def _physician_static_targets(contributions: dict) -> list[dict]:
    pheno = contributions.get("PhenoAge", {})
    if not pheno:
        return []
    ranked = sorted(pheno.items(), key=lambda kv: kv[1] or 0, reverse=True)
    targets = []
    for marker, contrib in ranked[:5]:
        if (contrib or 0) <= 0:
            continue
        targets.append({
            "target": f"Reduce {marker} contribution",
            "rationale": f"Currently driving {contrib:+.2f} yr PhenoAge "
                          "acceleration",
            "approach": "Discuss lifestyle, supplement, or pharmacologic "
                         "options targeting this marker; recheck in 3-4 months.",
        })
    return targets


def _two_col_table(doc, rows: list[tuple[str, str]]) -> None:
    tbl = doc.add_table(rows=len(rows), cols=2)
    for i, (k, v) in enumerate(rows):
        c1 = tbl.cell(i, 0)
        c2 = tbl.cell(i, 1)
        _set_cell_borders(c1, color="C7CCDB", size="2")
        _set_cell_borders(c2, color="C7CCDB", size="2")
        if i % 2 == 0:
            _shade_cell(c1, LIGHT_HEX)
            _shade_cell(c2, LIGHT_HEX)
        r1 = c1.paragraphs[0].add_run(k)
        r1.bold = True
        r1.font.size = Pt(10)
        r1.font.color.rgb = NAVY_RGB
        r2 = c2.paragraphs[0].add_run(v)
        r2.font.size = Pt(10)
        r2.font.color.rgb = DARK_RGB
