"""
INEXION patient + physician report generation - PDF output via ReportLab.

Two top-level functions:
- build_patient_report(...)   -> bytes (.pdf)
- build_physician_report(...) -> bytes (.pdf)

The Patient Report is a comprehensive INEXION-branded guidebook written in
patient-friendly language (~8th grade reading level). It explains every lab
value plainly and walks through biological / metabolic / liver / kidney age,
the normative reference percentile, and prioritized lifestyle recommendations.

The Physician Report is a clinical decision-support document at higher health
literacy. It surfaces biomarker contribution analysis (which markers most
accelerate or decelerate the patient's biological age across all four clocks)
and ranks intervention targets by predicted age delta improvement.

Numeric data (ages, deltas, percentiles, contribution magnitudes) is computed
deterministically from patient inputs; only the narrative interpretation is
generated by Claude, with a static fallback if the API call fails.

ReportLab implementation details:
- LETTER (8.5x11) with ~2cm margins => ~6.5" usable width
- Helvetica throughout for cross-platform consistency
- Tables use Paragraph cells for word-wrapped text
- Logo aspect ratio preserved via ImageReader.getSize()
"""
from __future__ import annotations
import io
import json
import os
from datetime import datetime
from typing import Any

from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.colors import HexColor
from reportlab.lib.units import inch, cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle,
    Image, HRFlowable, KeepTogether,
)
from reportlab.lib.utils import ImageReader

# ---------------------------------------------------------------------------
# INEXION brand constants - reportlab HexColor objects
# ---------------------------------------------------------------------------
NAVY    = HexColor("#0D1B3E")
GOLD    = HexColor("#C9941A")
LIGHT   = HexColor("#F2F4F8")
GREY    = HexColor("#6B7280")
DARK    = HexColor("#1A1A2E")
WHITE   = HexColor("#FFFFFF")
ROW_ALT = HexColor("#FAFAFC")
BORDER  = HexColor("#C7CCDB")

# Lab-status pastels for color-coded value cells. Backgrounds are tinted
# enough to scan at a glance without overpowering the surrounding text.
STATUS_GREEN_BG  = HexColor("#D4EDDA")
STATUS_YELLOW_BG = HexColor("#FFF3CD")
STATUS_RED_BG    = HexColor("#F8D7DA")
STATUS_GREEN_FG  = HexColor("#155724")
STATUS_YELLOW_FG = HexColor("#856404")
STATUS_RED_FG    = HexColor("#721C24")

# Page geometry
PAGE_W, PAGE_H = LETTER
LMARGIN = RMARGIN = 2.0 * cm
TMARGIN = BMARGIN = 1.8 * cm
USABLE_W = PAGE_W - LMARGIN - RMARGIN  # ~6.5"


# ---------------------------------------------------------------------------
# Lab metadata - patient-friendly explanations used both in the patient report
# (full text) and the physician report (short reference table). Values are
# keyed by the same names as the Patient Analysis page session state, minus
# the "pa_" prefix.
# ---------------------------------------------------------------------------
LAB_METADATA: dict[str, dict[str, Any]] = {
    "albumin": {
        "label": "Albumin",
        "units": "g/dL",
        "ref_range": "3.5 - 5.5",
        "patient_text": (
            "Albumin is a protein made by your liver. It helps carry nutrients, "
            "hormones, and medicines through your body. Higher levels usually mean "
            "your liver is healthy and you have good nutrition."
        ),
    },
    "creatinine": {
        "label": "Creatinine",
        "units": "mg/dL",
        "ref_range": "0.6 - 1.3",
        "patient_text": (
            "Creatinine is a waste product made by your muscles. Your kidneys filter "
            "it out of your blood. Higher levels can mean your kidneys are working "
            "harder than they should."
        ),
    },
    "glucose": {
        "label": "Glucose (fasting)",
        "units": "mg/dL",
        "ref_range": "70 - 99",
        "patient_text": (
            "Glucose is sugar in your blood. After fasting overnight, healthy levels "
            "stay below 100. Higher values can be an early sign of insulin resistance "
            "or diabetes."
        ),
    },
    "bun": {
        "label": "BUN",
        "units": "mg/dL",
        "ref_range": "7 - 20",
        "patient_text": (
            "BUN measures another waste product your kidneys clear. Together with "
            "creatinine it gives a fuller picture of how well your kidneys are working."
        ),
    },
    "uric_acid": {
        "label": "Uric acid",
        "units": "mg/dL",
        "ref_range": "3.5 - 7.2",
        "patient_text": (
            "Uric acid is a byproduct of breaking down purines (found in red meat, "
            "alcohol, and some seafood). Higher levels can cause gout and may signal "
            "metabolic issues."
        ),
    },
    "crp": {
        "label": "CRP",
        "units": "mg/L",
        "ref_range": "&lt; 3.0",
        "patient_text": (
            "CRP measures inflammation in your body. Chronic inflammation is one of "
            "the strongest accelerators of biological aging - lower is better."
        ),
    },
    "lymph": {
        "label": "Lymphocyte %",
        "units": "%",
        "ref_range": "20 - 40",
        "patient_text": (
            "Lymphocytes are immune cells that fight off infections. The percentage "
            "of lymphocytes in your white blood cells tells us about your immune "
            "system's health."
        ),
    },
    "wbc": {
        "label": "WBC",
        "units": "x1000/uL",
        "ref_range": "4.5 - 11.0",
        "patient_text": (
            "White blood cells fight infection. Levels that are too high or too low "
            "can both be concerning."
        ),
    },
    "mcv": {
        "label": "MCV",
        "units": "fL",
        "ref_range": "80 - 100",
        "patient_text": (
            "MCV measures the average size of your red blood cells. Larger or smaller "
            "than normal can point to nutritional deficiencies or other issues."
        ),
    },
    "rdw": {
        "label": "RDW",
        "units": "%",
        "ref_range": "11.5 - 14.5",
        "patient_text": (
            "RDW shows how much your red blood cells vary in size. Higher values are "
            "linked to faster aging and higher long-term risk."
        ),
    },
    "hba1c": {
        "label": "HbA1c",
        "units": "%",
        "ref_range": "&lt; 5.7",
        "patient_text": (
            "HbA1c shows your average blood sugar over the past 2-3 months. It's the "
            "best single number for tracking your blood sugar control."
        ),
    },
    "total_chol": {
        "label": "Total cholesterol",
        "units": "mg/dL",
        "ref_range": "&lt; 200",
        "patient_text": (
            "Total cholesterol is the sum of all cholesterol types in your blood. "
            "Lower values reduce heart disease risk - but the breakdown into HDL "
            "and LDL matters more."
        ),
    },
    "hdl": {
        "label": "HDL cholesterol",
        "units": "mg/dL",
        "ref_range": "&gt; 40 (M), &gt; 50 (F)",
        "patient_text": (
            "HDL is the 'good' cholesterol. It helps remove cholesterol buildup from "
            "your arteries. Higher is better."
        ),
    },
    "tbili": {
        "label": "Total bilirubin",
        "units": "mg/dL",
        "ref_range": "0.1 - 1.2",
        "patient_text": (
            "Bilirubin is a waste product your liver clears. Mildly higher levels "
            "can sometimes be protective; very high levels can signal liver issues."
        ),
    },
    "total_protein": {
        "label": "Total protein",
        "units": "g/dL",
        "ref_range": "6.0 - 8.3",
        "patient_text": (
            "Total protein measures all the proteins (including albumin) in your "
            "blood. Reflects nutrition status and liver / kidney function."
        ),
    },
    "alkphos": {
        "label": "Alkaline phosphatase",
        "units": "U/L",
        "ref_range": "40 - 130",
        "patient_text": (
            "An enzyme found in liver and bone. Elevated levels can signal liver, "
            "bone, or bile-duct problems."
        ),
    },
    "platelet": {
        "label": "Platelet count",
        "units": "x1000/uL",
        "ref_range": "150 - 400",
        "patient_text": (
            "Platelets help your blood clot when you cut yourself. Low or high "
            "counts can both have meaning."
        ),
    },
    "ldh": {
        "label": "LDH",
        "units": "U/L",
        "ref_range": "140 - 280",
        "patient_text": (
            "LDH is released when cells are damaged. Higher levels can be a "
            "non-specific marker of cellular stress."
        ),
    },
    "sbp": {
        "label": "Systolic BP",
        "units": "mmHg",
        "ref_range": "&lt; 120",
        "patient_text": (
            "Systolic is the top number in a blood pressure reading - the pressure "
            "when your heart beats. Lower is generally better."
        ),
    },
    "dbp": {
        "label": "Diastolic BP",
        "units": "mmHg",
        "ref_range": "&lt; 80",
        "patient_text": (
            "Diastolic is the bottom number - the pressure when your heart is at "
            "rest between beats."
        ),
    },
}


# ---------------------------------------------------------------------------
# Lab thresholds for status classification.
#   Green:  value within the typical-healthy band
#   Yellow: borderline / one tier outside (e.g. prediabetes for HbA1c)
#   Red:    significantly outside (e.g. clinical-cutoff diabetes range)
# Single-sided ranges (CRP, HbA1c, total chol, BPs) use 0 as the unused floor.
# HDL is sex-dependent and handled in _classify_lab().
# ---------------------------------------------------------------------------
LAB_THRESHOLDS: dict[str, dict[str, tuple[float, float]]] = {
    "albumin":       {"green": (3.5, 5.5),  "yellow": (3.0, 6.0)},
    "creatinine":    {"green": (0.6, 1.3),  "yellow": (0.5, 1.5)},
    "glucose":       {"green": (70, 99),    "yellow": (60, 125)},
    "bun":           {"green": (7, 20),     "yellow": (5, 26)},
    "uric_acid":     {"green": (3.5, 7.2),  "yellow": (3.0, 8.5)},
    "crp":           {"green": (0, 1.0),    "yellow": (0, 3.0)},
    "lymph":         {"green": (20, 40),    "yellow": (15, 50)},
    "wbc":           {"green": (4.5, 11),   "yellow": (3.5, 14)},
    "mcv":           {"green": (80, 100),   "yellow": (75, 105)},
    "rdw":           {"green": (11.5, 14.5),"yellow": (10, 16)},
    "hba1c":         {"green": (0, 5.7),    "yellow": (0, 6.4)},
    "total_chol":    {"green": (0, 200),    "yellow": (0, 239)},
    # HDL handled in _classify_lab() based on sex
    "tbili":         {"green": (0.1, 1.2),  "yellow": (0.1, 2.0)},
    "total_protein": {"green": (6.0, 8.3),  "yellow": (5.5, 9.0)},
    "alkphos":       {"green": (40, 130),   "yellow": (30, 200)},
    "platelet":      {"green": (150, 400),  "yellow": (100, 500)},
    "ldh":           {"green": (140, 280),  "yellow": (140, 400)},
    "sbp":           {"green": (0, 119),    "yellow": (0, 139)},
    "dbp":           {"green": (0, 79),     "yellow": (0, 89)},
}


def _classify_lab(key: str, value: float, sex: str = "Male") -> str:
    """Return 'green' | 'yellow' | 'red' | 'neutral' for a lab value."""
    if key == "hdl":
        # Sex-specific HDL cutoffs (NCEP / AHA convention)
        if sex == "Female":
            green_lo, yellow_lo = 50.0, 40.0
        else:
            green_lo, yellow_lo = 40.0, 35.0
        if value >= green_lo:
            return "green"
        if value >= yellow_lo:
            return "yellow"
        return "red"
    t = LAB_THRESHOLDS.get(key)
    if t is None:
        return "neutral"
    g_lo, g_hi = t["green"]
    y_lo, y_hi = t["yellow"]
    if g_lo <= value <= g_hi:
        return "green"
    if y_lo <= value <= y_hi:
        return "yellow"
    return "red"


# Patient-friendly labels + brief actionable hints for the 9 PhenoAge inputs.
# Used by the "What's Driving Your Biological Age" section to translate
# clinical marker names into something a non-clinician can act on.
PHENOAGE_PATIENT_LABEL = {
    "Albumin":              "Albumin (protein status)",
    "Creatinine":           "Creatinine (kidney filtration)",
    "Glucose":              "Glucose (blood sugar)",
    "CRP":                  "CRP (inflammation marker)",
    "Lymphocyte %":         "Lymphocyte % (immune balance)",
    "MCV":                  "MCV (red blood cell size)",
    "RDW":                  "RDW (red blood cell variation)",
    "Alkaline phosphatase": "Alkaline phosphatase (liver/bone enzyme)",
    "WBC":                  "WBC (white blood cell count)",
}

PHENOAGE_PATIENT_HINT = {
    "Albumin":              "Healthy levels reflect good nutrition and liver function.",
    "Creatinine":           "Reflects kidney filtration; hydration and muscle mass affect it.",
    "Glucose":              "Diet quality, sleep, and exercise are the biggest movers.",
    "CRP":                  "Driven by chronic inflammation - exercise, sleep, and a Mediterranean-style diet usually bring it down.",
    "Lymphocyte %":         "Reflects immune-system balance; chronic stress and infections can shift it.",
    "MCV":                  "Red cell size; B12, folate, and iron status matter most.",
    "RDW":                  "Variation in red cell size; reflects bone-marrow health.",
    "Alkaline phosphatase": "Liver and bone enzyme; usually responds to liver health and bone turnover.",
    "WBC":                  "Reflects immune activity; chronic stress and inflammation can elevate it.",
}


# ---------------------------------------------------------------------------
# Paragraph styles
# ---------------------------------------------------------------------------
def _build_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    return {
        "h1": ParagraphStyle(
            "h1", parent=base["Heading1"],
            fontName="Helvetica-Bold", fontSize=18, textColor=NAVY,
            spaceBefore=18, spaceAfter=6, leading=22,
        ),
        "h2": ParagraphStyle(
            "h2", parent=base["Heading2"],
            fontName="Helvetica-Bold", fontSize=11, textColor=NAVY,
            spaceBefore=14, spaceAfter=4, leading=14,
        ),
        "body": ParagraphStyle(
            "body", parent=base["BodyText"],
            fontName="Helvetica", fontSize=11, textColor=DARK,
            leading=15, spaceAfter=8, alignment=TA_LEFT,
        ),
        "body_lg": ParagraphStyle(
            "body_lg", parent=base["BodyText"],
            fontName="Helvetica", fontSize=12, textColor=DARK,
            leading=17, spaceAfter=10, alignment=TA_LEFT,
        ),
        "small": ParagraphStyle(
            "small", parent=base["BodyText"],
            fontName="Helvetica-Oblique", fontSize=9, textColor=GREY,
            leading=12, spaceAfter=4,
        ),
        "rec": ParagraphStyle(
            "rec", parent=base["BodyText"],
            fontName="Helvetica", fontSize=11, textColor=DARK,
            leading=15, spaceAfter=8, leftIndent=20,
        ),
        "tablecell": ParagraphStyle(
            "tablecell", parent=base["BodyText"],
            fontName="Helvetica", fontSize=9, textColor=DARK,
            leading=11, alignment=TA_LEFT,
        ),
        "tablecell_bold": ParagraphStyle(
            "tablecell_bold", parent=base["BodyText"],
            fontName="Helvetica-Bold", fontSize=9, textColor=DARK,
            leading=11, alignment=TA_LEFT,
        ),
        "tablehead": ParagraphStyle(
            "tablehead", parent=base["BodyText"],
            fontName="Helvetica-Bold", fontSize=10, textColor=WHITE,
            leading=12, alignment=TA_LEFT,
        ),
        "barbig": ParagraphStyle(
            "barbig", fontName="Helvetica-Bold", fontSize=22,
            textColor=WHITE, alignment=TA_CENTER, leading=26,
        ),
        "barsm_gold": ParagraphStyle(
            "barsm_gold", fontName="Helvetica-Bold", fontSize=10,
            textColor=GOLD, alignment=TA_CENTER, leading=12,
        ),
        "barsm_white": ParagraphStyle(
            "barsm_white", fontName="Helvetica", fontSize=10,
            textColor=WHITE, alignment=TA_CENTER, leading=12,
        ),
    }


# ---------------------------------------------------------------------------
# Building blocks
# ---------------------------------------------------------------------------
def _cover_block(styles, logo_path: str | None, report_label: str,
                  patient_age: int, patient_sex: str, patient_race: str = ""):
    """Logo + navy title bar + gold rule. Returns a list of flowables."""
    flows = []
    if logo_path and os.path.exists(logo_path):
        try:
            ir = ImageReader(logo_path)
            iw, ih = ir.getSize()
            target_w = 2.6 * inch
            target_h = target_w * (ih / iw)
            img = Image(logo_path, width=target_w, height=target_h)
            img.hAlign = "CENTER"
            flows.append(img)
            flows.append(Spacer(1, 0.25 * inch))
        except Exception:
            pass

    today = datetime.now().strftime("%B %d, %Y")
    demo_bits = [f"Age {patient_age}", patient_sex]
    if patient_race:
        demo_bits.append(patient_race)
    demo_line = " | ".join(demo_bits) + "  ·  " + today

    bar_data = [
        [Paragraph("INEXION LONGEVITY REGISTRY", styles["barsm_gold"])],
        [Paragraph(report_label, styles["barbig"])],
        [Paragraph(demo_line, styles["barsm_white"])],
    ]
    bar = Table(bar_data, colWidths=[USABLE_W])
    bar.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), NAVY),
        ("TOPPADDING",    (0, 0), (-1, 0),  14),
        ("BOTTOMPADDING", (0, 0), (-1, 0),  4),
        ("TOPPADDING",    (0, 1), (-1, 1),  4),
        ("BOTTOMPADDING", (0, 1), (-1, 1),  4),
        ("TOPPADDING",    (0, 2), (-1, 2),  4),
        ("BOTTOMPADDING", (0, 2), (-1, 2),  14),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 12),
    ]))
    flows.append(bar)
    flows.append(Spacer(1, 0.18 * inch))
    flows.append(HRFlowable(width="100%", thickness=2, color=GOLD,
                              spaceBefore=0, spaceAfter=10))
    return flows


def _data_table(headers: list[str], rows: list[list[str]],
                  col_widths: list[float], styles) -> Table:
    """Branded table with navy header row, alternating row shading,
    soft borders, and word-wrapped Paragraph cells."""
    head_cells = [Paragraph(h, styles["tablehead"]) for h in headers]
    body_cells = []
    for r in rows:
        body_cells.append([
            Paragraph(str(cell), styles["tablecell"]) for cell in r
        ])
    table = Table([head_cells] + body_cells, colWidths=col_widths,
                   repeatRows=1)
    style_cmds = [
        ("BACKGROUND",    (0, 0), (-1, 0),  NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0),  WHITE),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("BOX",           (0, 0), (-1, -1), 0.5, BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.25, BORDER),
    ]
    for i in range(1, len(rows) + 1):
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), ROW_ALT))
    table.setStyle(TableStyle(style_cmds))
    return table


def _kv_table(rows: list[tuple[str, str]], styles,
               col_widths: tuple[float, float] | None = None) -> Table:
    """Simple two-column key/value table with navy bold keys."""
    if col_widths is None:
        col_widths = (USABLE_W * 0.42, USABLE_W * 0.58)
    body = []
    for k, v in rows:
        body.append([
            Paragraph(f"<b><font color='#0D1B3E'>{k}</font></b>",
                       styles["tablecell"]),
            Paragraph(str(v), styles["tablecell"]),
        ])
    table = Table(body, colWidths=list(col_widths))
    style_cmds = [
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("BOX",           (0, 0), (-1, -1), 0.5, BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.25, BORDER),
    ]
    for i in range(len(body)):
        if i % 2 == 0:
            style_cmds.append(("BACKGROUND", (0, i), (-1, i), ROW_ALT))
    table.setStyle(TableStyle(style_cmds))
    return table


def _disclaimer(text: str, styles) -> list:
    return [
        Spacer(1, 0.1 * inch),
        HRFlowable(width="100%", thickness=1, color=GOLD,
                    spaceBefore=4, spaceAfter=8),
        Paragraph(text, styles["small"]),
    ]


# ---------------------------------------------------------------------------
# Page header / footer with INEXION branding (drawn on every page)
# ---------------------------------------------------------------------------
def _make_on_page(report_label: str, patient_summary: str):
    def _draw(canvas, doc):
        canvas.saveState()
        # Top thin gold rule
        canvas.setStrokeColor(GOLD)
        canvas.setLineWidth(1.5)
        canvas.line(LMARGIN, PAGE_H - 0.6 * cm,
                     PAGE_W - RMARGIN, PAGE_H - 0.6 * cm)
        # Footer text
        canvas.setFillColor(GREY)
        canvas.setFont("Helvetica", 8)
        footer = f"INEXION Longevity Registry  ·  {report_label}  ·  {patient_summary}"
        canvas.drawString(LMARGIN, 0.8 * cm, footer)
        canvas.drawRightString(PAGE_W - RMARGIN, 0.8 * cm,
                                f"Page {doc.page}")
        canvas.restoreState()
    return _draw


# ---------------------------------------------------------------------------
# Claude narrative generation
# ---------------------------------------------------------------------------
# Opus is used for report narrative because clinical-quality writing matters
# more here than latency or cost. The prompts ask for nuanced patient education
# at controlled reading levels and quantitative clinical reasoning - Opus
# handles both reliably; Haiku occasionally drops sections or breaks the JSON
# contract under longer outputs.
REPORT_MODEL = "claude-opus-4-6"


def _claude_call(system: str, user: str, max_tokens: int = 3500) -> dict | None:
    """Single Opus call expecting a JSON object back. Returns None on failure."""
    api_key = os.environ.get("ANTHROPIC_API_KEY", "")
    if not api_key:
        return None
    try:
        import anthropic
        client = anthropic.Anthropic(api_key=api_key)
        resp = client.messages.create(
            model=REPORT_MODEL,
            max_tokens=max_tokens,
            system=system,
            messages=[{"role": "user", "content": user}],
        )
        raw = resp.content[0].text.strip()
        if raw.startswith("```"):
            raw = "\n".join(raw.split("\n")[1:])
        if raw.endswith("```"):
            raw = "\n".join(raw.split("\n")[:-1])
        return json.loads(raw)
    except Exception:
        return None


def _generate_patient_narrative(ctx: dict) -> dict:
    system = (
        "You are a longevity clinic patient educator at INEXION, a longevity-focused "
        "medical practice. Write in clear, encouraging, patient-friendly language at "
        "approximately an 8th-grade reading level. Be honest about findings without "
        "being alarming. Avoid jargon; when you must use a medical term, briefly "
        "explain it. Always return strictly valid JSON with no markdown fences."
    )
    user = (
        "Generate patient-facing report content for a longevity clinic visit. "
        "Patient context (JSON):\n"
        f"{json.dumps(ctx, indent=2, default=str)}\n\n"
        "Return a JSON object with these exact keys:\n"
        "{\n"
        '  "executive_summary": "2-3 plain-language sentences summarizing where the '
        'patient stands biologically vs their chronological age",\n'
        '  "biological_age_narrative": "3-4 short paragraphs explaining biological '
        'age vs chronological age, what the patient\'s delta means for their '
        'healthspan, and how to interpret the population percentile. Separate '
        'paragraphs with double newlines.",\n'
        '  "organ_ages_narrative": "2-3 short paragraphs comparing the patient\'s '
        'metabolic, liver, and kidney ages and what each tells them. Separate '
        'paragraphs with double newlines.",\n'
        '  "intervention_summary": "1-2 paragraphs explaining how lifestyle changes '
        'can move biological age in their favor, written hopefully and concretely",\n'
        '  "recommendations": ["5 to 7 specific actionable lifestyle / health '
        "recommendations ordered by likely impact, each one a single complete "
        'sentence the patient can act on this month"]\n'
        "}\n"
        "Do NOT include markdown fences. Return the JSON only."
    )
    return _claude_call(system, user, max_tokens=3500) or {}


def _generate_physician_narrative(ctx: dict) -> dict:
    system = (
        "You are a clinical decision-support assistant for longevity-medicine "
        "clinicians at INEXION, a longevity-focused medical practice. The reading "
        "audience is a board-certified physician practicing longevity medicine, "
        "comfortable with off-label gerotherapeutics and willing to consider "
        "rapamycin, acarbose, metformin, GLP-1 agonists, SGLT2 inhibitors, "
        "senolytics (dasatinib + quercetin), NAD precursors (NMN, NR), and other "
        "longevity-medicine pharmacotherapies where evidence supports the "
        "biomarker pathway being addressed. Write precisely, quantitatively, and "
        "action-oriented. Cite contribution magnitudes by name. Always return "
        "strictly valid JSON with no markdown fences."
    )
    user = (
        "Generate clinical decision-support content for a longevity clinic patient "
        "visit. Patient + biomarker contribution context (JSON):\n"
        f"{json.dumps(ctx, indent=2, default=str)}\n\n"
        "Return a JSON object with these exact keys:\n"
        "{\n"
        '  "executive_summary": "2-3 sentence clinical summary including PhenoAge, '
        'delta vs chronological, and the single highest-magnitude age accelerator",\n'
        '  "biomarker_analysis": "2-3 paragraphs identifying which biomarkers most '
        'strongly accelerate AND decelerate this patient\'s biological age across '
        'all four clocks. Be quantitative - cite specific contribution magnitudes. '
        'Separate paragraphs with double newlines.",\n'
        '  "intervention_targets": [\n'
        '     {"target": "<specific biomarker target value, e.g. \'Reduce hsCRP to '
        '<1.0 mg/L\'>", '
        '"rationale": "<why this is the priority - cite contribution magnitude>", '
        '"approach": "<lifestyle baseline + nutraceutical options (e.g. omega-3, '
        'curcumin, berberine, bergamot)>", '
        '"longevity_rx": "<specific longevity-medicine pharmacologic options to '
        'consider for this target. Be concrete: name agents (rapamycin, acarbose, '
        'metformin, semaglutide/tirzepatide, empagliflozin, dasatinib+quercetin, '
        'NMN, NR, low-dose lithium, low-dose naltrexone, statins, fibrates, etc.) '
        'with brief mechanism against this biomarker pathway. Note off-label '
        'status. If pharmacotherapy is not warranted for this target, write '
        '\'No pharmacologic intervention warranted at this stage.\'>"}\n'
        "  ],\n"
        '  "follow_up": "2-3 sentences on repeat testing cadence (typical: 3-4 '
        'months for biomarker recheck), any specialist referrals worth considering, '
        "and which contribution to monitor most closely after intervention\"\n"
        "}\n"
        "Provide 4-6 intervention_targets ranked by predicted age-delta impact. "
        "Tailor longevity_rx to this specific patient's biomarker profile - do not "
        "list every gerotherapeutic. Match agent to target pathway: e.g., if "
        "glucose is the top accelerator, lead with metformin / acarbose / GLP-1; "
        "if inflammation, consider rapamycin + omega-3; if metabolic syndrome, "
        "GLP-1 + SGLT2. Do NOT include markdown fences. Return the JSON only."
    )
    return _claude_call(system, user, max_tokens=3500) or {}


# ---------------------------------------------------------------------------
# Static fallback narrative (used when the Claude call is unavailable)
# ---------------------------------------------------------------------------
def _delta_phrase(delta: float | None) -> str:
    if delta is None:
        return "—"
    if delta < -1.0:
        return f"{abs(delta):.1f} years younger biologically"
    if delta > 1.0:
        return f"{abs(delta):.1f} years older biologically"
    return "essentially aligned with chronological age"


def _patient_static_summary(phenoage: dict, organ_ages: dict) -> str:
    delta = phenoage.get("delta", 0)
    if delta < -2:
        bottom = ("Your biological-age results are encouraging - your body is "
                  "tracking younger than your calendar age.")
    elif delta > 2:
        bottom = ("Your biological-age results suggest your body is aging "
                  "faster than your calendar age - there's real opportunity "
                  "to slow this down.")
    else:
        bottom = ("Your biological-age results sit close to your calendar age. "
                  "Targeted lifestyle changes can move them in your favor.")
    return (
        f"Your PhenoAge is {phenoage.get('phenoage', 0):.1f} years compared to a "
        f"chronological age that's {_delta_phrase(delta)}. {bottom}"
    )


def _patient_static_bio(patient: dict, phenoage: dict,
                          percentile: int | None) -> str:
    delta = phenoage.get("delta", 0)
    pct = (
        f"You sit at the {percentile}th percentile of a matched comparison "
        "group (same age, sex, and ancestry). Lower percentiles are better - "
        "they mean fewer people in your matched group are aging as well as "
        "you are." if percentile is not None else ""
    )
    return (
        "Biological age uses your blood markers to estimate how well your "
        "body is functioning. It can run faster or slower than your calendar "
        "age depending on inflammation, metabolism, organ stress, and "
        "lifestyle factors.\n\n"
        f"Your PhenoAge of {phenoage.get('phenoage', 0):.1f} years versus a "
        f"chronological age of {patient.get('age', 0)} years means you're "
        f"{_delta_phrase(delta)}. The single biggest reason biological age "
        "shifts is chronic inflammation and metabolic strain, which tend to "
        "respond well to diet, exercise, sleep, and stress management.\n\n"
        f"{pct}"
    )


def _patient_static_organs(organ_ages: dict) -> str:
    bits = []
    for label, k_age, k_d in [("metabolic", "metabolic_age", "metabolic_delta"),
                                ("liver",     "liver_age",     "liver_delta"),
                                ("kidney",    "kidney_age",    "kidney_delta")]:
        a = organ_ages.get(k_age)
        d = organ_ages.get(k_d, 0)
        if a is None:
            continue
        bits.append(
            f"Your {label} age is {a:.1f} years - "
            f"{_delta_phrase(d)} on this organ system."
        )
    if not bits:
        return ("Organ age estimates were not available for this report. "
                "Talk with your clinician about which organ-specific "
                "biomarkers might be worth tracking.")
    return " ".join(bits)


def _patient_static_recs(contributions: dict) -> list[str]:
    return [
        "Aim for 150 minutes of moderate-intensity exercise per week plus 2 "
        "strength-training sessions - exercise is the single most consistent "
        "biological-age decelerator across studies.",
        "Anchor meals around protein, fiber, and colorful plants; minimize "
        "ultra-processed foods, which drive inflammation and accelerate aging.",
        "Protect 7-9 hours of sleep on a consistent schedule; sleep debt "
        "directly elevates inflammatory markers and accelerates biological age.",
        "If you drink alcohol, hold it to 3 drinks per week or less - alcohol "
        "is a major driver of liver-age acceleration in registry data.",
        "Schedule a follow-up lab panel in 3-4 months to see how these changes "
        "are reflected in your biomarkers.",
    ]


def _physician_static_summary(phenoage: dict, organ_ages: dict,
                                contributions: dict) -> str:
    delta = phenoage.get("delta", 0)
    pheno = contributions.get("PhenoAge", {})
    if pheno:
        top = max(pheno.items(), key=lambda kv: abs(kv[1] or 0))
        top_str = f" Top accelerator: {top[0]} ({top[1]:+.2f} yr)."
    else:
        top_str = ""
    return (
        f"PhenoAge {phenoage.get('phenoage', 0):.2f} yr "
        f"(Δ {delta:+.2f} vs chronological); "
        f"10y mortality {phenoage.get('mortality_10y', 0)*100:.2f}%."
        f"{top_str}"
    )


def _physician_static_bio(contributions: dict) -> str:
    lines = []
    for clock, contrib in (contributions or {}).items():
        if not contrib:
            continue
        ranked = sorted(contrib.items(),
                         key=lambda kv: abs(kv[1] or 0), reverse=True)
        top3 = ranked[:3]
        bits = ", ".join(f"{m} ({v:+.2f})" for m, v in top3)
        lines.append(f"<b>{clock}:</b> {bits}.")
    if not lines:
        return ("Per-clock contribution data was not available; refer to the "
                "Patient Analysis app for detailed waterfall plots.")
    return "Top contributors by absolute magnitude across each clock:\n\n" + \
           "\n\n".join(lines)


def _physician_static_targets(contributions: dict) -> list[dict]:
    """Fallback targets when Claude is unavailable. Pairs each top accelerator
    with the most-mechanistically-aligned longevity Rx options."""
    pheno = contributions.get("PhenoAge", {})
    if not pheno:
        return []
    # Mechanism-driven Rx hints keyed by PhenoAge biomarker.
    rx_hints = {
        "Glucose":      "Metformin (off-label longevity), acarbose, low-dose GLP-1 "
                         "agonists; SGLT2 inhibitor if comorbid CV/renal risk.",
        "CRP":          "Rapamycin (off-label, mTOR-mediated inflammation reduction), "
                         "high-dose omega-3 (EPA/DHA 2-4 g/d), low-dose statin if CV "
                         "risk warrants.",
        "Creatinine":   "If trending up: SGLT2 inhibitor for renoprotection; review "
                         "supplement load; recheck cystatin C.",
        "Albumin":      "Address underlying nutrition or inflammation; rarely a "
                         "primary pharmacologic target.",
        "Lymphocyte %": "Rule out chronic viral burden; consider rapamycin if "
                         "immunosenescence pattern (low lymph + high RDW).",
        "MCV":          "B12/folate if macrocytic; iron studies if microcytic. "
                         "Pharmacotherapy guided by underlying cause.",
        "RDW":          "Iron / B12 / folate workup; rapamycin candidate if "
                         "elevated with low lymphocytes.",
        "Alkaline phosphatase": "Liver vs. bone fractionation; if hepatic, address "
                                 "metabolic dysfunction-associated steatohepatitis "
                                 "(MASH) - consider GLP-1, vitamin E, semaglutide.",
        "WBC":          "Address inflammation pathway upstream; rapamycin and "
                         "omega-3 if chronic elevation.",
    }
    ranked = sorted(pheno.items(), key=lambda kv: kv[1] or 0, reverse=True)
    targets = []
    for marker, contrib in ranked[:5]:
        if (contrib or 0) <= 0:
            continue
        targets.append({
            "target": f"Reduce {marker} contribution",
            "rationale": f"Currently driving {contrib:+.2f} yr PhenoAge "
                          "acceleration",
            "approach": "Lifestyle: optimize sleep, exercise (Z2 + resistance), "
                         "Mediterranean-style diet, time-restricted eating. Recheck "
                         "in 3-4 months.",
            "longevity_rx": rx_hints.get(
                marker, "Match longevity Rx to underlying pathway driving this "
                         "biomarker; review off-label evidence with patient."),
        })
    return targets


# ---------------------------------------------------------------------------
# Status-aware lab table builder. Tints the value cell green/yellow/red
# based on _classify_lab() and uses the matched dark text color for legibility.
# ---------------------------------------------------------------------------
def _status_lab_table(headers: list[str], rows: list[list[str]],
                       statuses: list[str], value_col_idx: int,
                       col_widths: list[float], styles,
                       status_col_idx: int | None = None) -> Table:
    """Branded lab table with per-row tinted cells driven by `statuses`.
    `value_col_idx` is the column index of the patient's value (gets the
    pastel background). `status_col_idx`, if provided, also gets tinted."""
    head_cells = [Paragraph(h, styles["tablehead"]) for h in headers]
    body_cells = [
        [Paragraph(str(c), styles["tablecell"]) for c in r] for r in rows
    ]
    table = Table([head_cells] + body_cells, colWidths=col_widths,
                   repeatRows=1)
    bg_for_status = {
        "green":  STATUS_GREEN_BG,
        "yellow": STATUS_YELLOW_BG,
        "red":    STATUS_RED_BG,
    }
    style_cmds = [
        ("BACKGROUND",    (0, 0), (-1, 0),  NAVY),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("BOX",           (0, 0), (-1, -1), 0.5, BORDER),
        ("INNERGRID",     (0, 0), (-1, -1), 0.25, BORDER),
    ]
    for i, status in enumerate(statuses, start=1):
        bg = bg_for_status.get(status)
        if bg:
            style_cmds.append(("BACKGROUND", (value_col_idx, i),
                                 (value_col_idx, i), bg))
            if status_col_idx is not None:
                style_cmds.append(("BACKGROUND", (status_col_idx, i),
                                     (status_col_idx, i), bg))
        else:
            # Neutral rows still get alternating shading so they don't read flat
            if i % 2 == 0:
                style_cmds.append(("BACKGROUND", (0, i), (-1, i), ROW_ALT))
    table.setStyle(TableStyle(style_cmds))
    return table


def _status_label(status: str) -> str:
    """Patient-friendly label string for a lab status code."""
    return {
        "green":   "Normal",
        "yellow":  "Borderline",
        "red":     "Outside normal",
        "neutral": "—",
    }.get(status, "—")


# ---------------------------------------------------------------------------
# PATIENT REPORT
# ---------------------------------------------------------------------------
def build_patient_report(
    *,
    patient: dict,
    labs: dict,
    phenoage: dict,
    organ_ages: dict,
    contributions: dict,
    percentile: int | None = None,
    logo_path: str | None = None,
) -> bytes:
    """Build the comprehensive patient guidebook PDF and return as bytes."""
    ctx = {"patient": patient, "labs": labs, "phenoage": phenoage,
           "organ_ages": organ_ages, "contributions": contributions,
           "percentile": percentile}
    narrative = _generate_patient_narrative(ctx)
    styles = _build_styles()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=LETTER,
        leftMargin=LMARGIN, rightMargin=RMARGIN,
        topMargin=TMARGIN, bottomMargin=BMARGIN,
        title="INEXION Patient Report",
        author="INEXION Longevity Registry",
    )

    flow = []

    # ----- Cover -----
    flow.extend(_cover_block(
        styles, logo_path, "Patient Report",
        patient_age=patient.get("age", 0),
        patient_sex=patient.get("sex", ""),
        patient_race=patient.get("race", ""),
    ))

    # ----- Executive summary -----
    flow.append(Paragraph("Your Results at a Glance", styles["h1"]))
    exec_summary = narrative.get("executive_summary") or \
                   _patient_static_summary(phenoage, organ_ages)
    flow.append(Paragraph(exec_summary, styles["body_lg"]))

    # Snapshot table - chronological vs each clock
    flow.append(Paragraph("YOUR AGES — CHRONOLOGICAL VS BIOLOGICAL",
                            styles["h2"]))
    snap_rows = [
        ["Chronological age", f"{patient.get('age', 0)} years",
         "Your age in calendar years."],
        ["Biological age (PhenoAge)",
         f"{phenoage.get('phenoage', 0):.1f} years",
         _delta_phrase(phenoage.get("delta", 0))],
    ]
    if organ_ages.get("metabolic_age") is not None:
        snap_rows.append(["Metabolic age",
                            f"{organ_ages['metabolic_age']:.1f} years",
                            _delta_phrase(organ_ages.get("metabolic_delta"))])
    if organ_ages.get("liver_age") is not None:
        snap_rows.append(["Liver age",
                            f"{organ_ages['liver_age']:.1f} years",
                            _delta_phrase(organ_ages.get("liver_delta"))])
    if organ_ages.get("kidney_age") is not None:
        snap_rows.append(["Kidney age",
                            f"{organ_ages['kidney_age']:.1f} years",
                            _delta_phrase(organ_ages.get("kidney_delta"))])

    flow.append(_data_table(
        ["Measurement", "Your value", "What it means"],
        snap_rows,
        col_widths=[USABLE_W * 0.30, USABLE_W * 0.20, USABLE_W * 0.50],
        styles=styles,
    ))

    if phenoage.get("mortality_10y") is not None:
        flow.append(Spacer(1, 0.10 * inch))
        flow.append(Paragraph(
            f"Estimated 10-year all-cause mortality risk: "
            f"<b>{phenoage.get('mortality_10y', 0)*100:.1f}%</b> "
            "(modeled from PhenoAge).",
            styles["small"],
        ))

    if percentile is not None:
        flow.append(Paragraph(
            f"Population percentile: you sit at the <b>{percentile}th "
            f"percentile</b> vs a matched-cohort reference (same age, sex, "
            "and ancestry). A lower percentile is better.",
            styles["body"],
        ))

    flow.append(Spacer(1, 0.1 * inch))

    # ----- Biological age narrative -----
    flow.append(Paragraph("Understanding Your Biological Age", styles["h1"]))
    bio_text = narrative.get("biological_age_narrative") or \
               _patient_static_bio(patient, phenoage, percentile)
    for para in [p.strip() for p in bio_text.split("\n\n") if p.strip()]:
        flow.append(Paragraph(para, styles["body"]))

    # ----- Organ ages narrative -----
    flow.append(Paragraph("Your Organ Ages", styles["h1"]))
    organ_text = narrative.get("organ_ages_narrative") or \
                 _patient_static_organs(organ_ages)
    for para in [p.strip() for p in organ_text.split("\n\n") if p.strip()]:
        flow.append(Paragraph(para, styles["body"]))

    # ----- What's Driving Your Biological Age -----
    # Two ranked lists: decelerators (helpers, green) and accelerators (focus
    # areas, red), built from the PhenoAge contributions dict. Patient-friendly
    # marker labels and one-line action hints make the section actionable
    # without requiring clinical knowledge.
    pheno_contrib = (contributions or {}).get("PhenoAge", {})
    if pheno_contrib:
        flow.append(Paragraph("What's Driving Your Biological Age",
                                styles["h1"]))
        flow.append(Paragraph(
            "Different lab values pull your biological age up or down. The "
            "markers below show which ones are working in your favor (helping "
            "you stay biologically younger) versus which ones are pulling your "
            "age up. Focusing on the right side is where the biggest "
            "healthspan wins live.",
            styles["body"],
        ))

        # Sort: most-negative-first for decelerators, most-positive-first for accelerators
        sorted_contrib = sorted(pheno_contrib.items(), key=lambda kv: kv[1])
        decelerators = [(m, c) for m, c in sorted_contrib if (c or 0) < -0.05][:4]
        accelerators = list(reversed(
            [(m, c) for m, c in sorted_contrib if (c or 0) > 0.05]))[:4]

        # WORKING IN YOUR FAVOR (green)
        flow.append(Paragraph(
            "<b><font color='#155724'>WORKING IN YOUR FAVOR</font></b> "
            "&mdash; helping you stay biologically younger",
            styles["h2"],
        ))
        if decelerators:
            for marker, contrib in decelerators:
                label = PHENOAGE_PATIENT_LABEL.get(marker, marker)
                hint  = PHENOAGE_PATIENT_HINT.get(marker, "")
                line = (
                    f"<b>{label}</b> &nbsp; "
                    f"<font color='#155724'><b>{contrib:+.2f} years</b></font> "
                    f"impact on biological age<br/>"
                    f"<font color='#6B7280' size='9'><i>{hint}</i></font>"
                )
                flow.append(Paragraph(line, styles["rec"]))
        else:
            flow.append(Paragraph(
                "No markers are significantly decelerating your biological "
                "age right now.", styles["body"]))

        # FOCUS AREAS (red)
        flow.append(Paragraph(
            "<b><font color='#721C24'>FOCUS AREAS</font></b> &mdash; pulling "
            "your age up",
            styles["h2"],
        ))
        if accelerators:
            for marker, contrib in accelerators:
                label = PHENOAGE_PATIENT_LABEL.get(marker, marker)
                hint  = PHENOAGE_PATIENT_HINT.get(marker, "")
                line = (
                    f"<b>{label}</b> &nbsp; "
                    f"<font color='#721C24'><b>+{contrib:.2f} years</b></font> "
                    f"impact on biological age<br/>"
                    f"<font color='#6B7280' size='9'><i>{hint}</i></font>"
                )
                flow.append(Paragraph(line, styles["rec"]))
        else:
            flow.append(Paragraph(
                "No markers are significantly accelerating your biological "
                "age right now - keep doing what you're doing.",
                styles["body"]))

    # ----- Lab explanations -----
    flow.append(Paragraph("Your Lab Results Explained", styles["h1"]))
    flow.append(Paragraph(
        "Each lab below shows your value with a color status: "
        "<font color='#155724'><b>green = normal</b></font>, "
        "<font color='#856404'><b>yellow = borderline</b></font>, or "
        "<font color='#721C24'><b>red = outside the typical healthy range</b></font>. "
        "The plain-language explanation tells you what the test is measuring.",
        styles["body"],
    ))

    pat_sex = patient.get("sex", "Male")
    lab_rows = []
    statuses = []
    for key, meta in LAB_METADATA.items():
        val = labs.get(key)
        if val is None:
            continue
        try:
            val_f = float(val)
            val_str = f"{val_f:.2f} {meta['units']}"
            status = _classify_lab(key, val_f, pat_sex)
        except (TypeError, ValueError):
            val_str = str(val)
            status = "neutral"
        lab_rows.append([
            f"<b>{meta['label']}</b>",
            val_str,
            _status_label(status),
            meta["ref_range"],
            meta["patient_text"],
        ])
        statuses.append(status)

    if lab_rows:
        flow.append(_status_lab_table(
            headers=["Test", "Your value", "Status", "Typical range",
                      "What it means"],
            rows=lab_rows,
            statuses=statuses,
            value_col_idx=1,
            status_col_idx=2,
            col_widths=[USABLE_W * 0.16, USABLE_W * 0.13, USABLE_W * 0.13,
                          USABLE_W * 0.14, USABLE_W * 0.44],
            styles=styles,
        ))

    # ----- What you can do -----
    flow.append(PageBreak())
    flow.append(Paragraph("What You Can Do This Month", styles["h1"]))
    int_summary = narrative.get("intervention_summary")
    if int_summary:
        flow.append(Paragraph(int_summary, styles["body"]))

    recs = narrative.get("recommendations") or _patient_static_recs(contributions)
    for i, rec in enumerate(recs, start=1):
        flow.append(Paragraph(
            f"<font color='#C9941A'><b>{i}.</b></font>&nbsp;&nbsp;{rec}",
            styles["rec"],
        ))

    # ----- Disclaimer -----
    flow.extend(_disclaimer(
        "This report is for educational purposes only and does not replace "
        "medical advice from a licensed clinician. Biological-age estimates "
        "are population models with confidence intervals; results may shift "
        "modestly between visits. Discuss any changes to medication, "
        "supplementation, or activity with your INEXION clinician before "
        "acting on these recommendations.",
        styles,
    ))

    summary_str = (
        f"Patient Report  ·  Age {patient.get('age', 0)} {patient.get('sex', '')}"
    )
    on_page = _make_on_page("Patient Report", summary_str)
    doc.build(flow, onFirstPage=on_page, onLaterPages=on_page)
    buf.seek(0)
    return buf.read()


# ---------------------------------------------------------------------------
# PHYSICIAN REPORT
# ---------------------------------------------------------------------------
def build_physician_report(
    *,
    patient: dict,
    labs: dict,
    phenoage: dict,
    organ_ages: dict,
    contributions: dict,
    percentile: int | None = None,
    logo_path: str | None = None,
) -> bytes:
    """Build the clinical decision-support PDF and return as bytes."""
    ctx = {"patient": patient, "labs": labs, "phenoage": phenoage,
           "organ_ages": organ_ages, "contributions": contributions,
           "percentile": percentile}
    narrative = _generate_physician_narrative(ctx)
    styles = _build_styles()

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=LETTER,
        leftMargin=LMARGIN, rightMargin=RMARGIN,
        topMargin=TMARGIN, bottomMargin=BMARGIN,
        title="INEXION Physician Report",
        author="INEXION Longevity Registry",
    )

    flow = []

    flow.extend(_cover_block(
        styles, logo_path, "Physician Report",
        patient_age=patient.get("age", 0),
        patient_sex=patient.get("sex", ""),
        patient_race=patient.get("race", ""),
    ))

    # ----- Executive summary -----
    flow.append(Paragraph("Executive Summary", styles["h1"]))
    summary = narrative.get("executive_summary") or \
              _physician_static_summary(phenoage, organ_ages, contributions)
    flow.append(Paragraph(summary, styles["body"]))

    # ----- Biological Age Profile (KV table) -----
    flow.append(Paragraph("BIOLOGICAL AGE PROFILE", styles["h2"]))
    chrono = patient.get("age", 0)
    kv_rows: list[tuple[str, str]] = [
        ("Chronological age (yr)", f"{chrono}"),
        ("PhenoAge (yr)",
         f"{phenoage.get('phenoage', 0):.2f}  "
         f"(Δ {phenoage.get('delta', 0):+.2f})"),
    ]
    if phenoage.get("mortality_10y") is not None:
        kv_rows.append(
            ("10-yr mortality risk",
             f"{phenoage.get('mortality_10y', 0)*100:.2f}%")
        )
    if percentile is not None:
        kv_rows.append(
            ("Population percentile",
             f"{percentile}th  (matched age × sex × race)")
        )
    if organ_ages.get("metabolic_age") is not None:
        kv_rows.append(
            ("Metabolic age (yr)",
             f"{organ_ages['metabolic_age']:.2f}  "
             f"(Δ {organ_ages.get('metabolic_delta', 0):+.2f})")
        )
    if organ_ages.get("liver_age") is not None:
        kv_rows.append(
            ("Liver age (yr)",
             f"{organ_ages['liver_age']:.2f}  "
             f"(Δ {organ_ages.get('liver_delta', 0):+.2f})")
        )
    if organ_ages.get("kidney_age") is not None:
        kv_rows.append(
            ("Kidney age (yr)",
             f"{organ_ages['kidney_age']:.2f}  "
             f"(Δ {organ_ages.get('kidney_delta', 0):+.2f})")
        )
    flow.append(_kv_table(kv_rows, styles))

    # ----- Biomarker contribution analysis -----
    flow.append(Paragraph("Biomarker Contribution Analysis", styles["h1"]))
    bio_text = narrative.get("biomarker_analysis") or \
               _physician_static_bio(contributions)
    for para in [p.strip() for p in bio_text.split("\n\n") if p.strip()]:
        flow.append(Paragraph(para, styles["body"]))

    # Per-clock contribution tables (sorted by absolute Δ-years).
    # Red BG for accelerators, green BG for decelerators, no tint for neutral.
    for clock_name, clock_contrib in (contributions or {}).items():
        if not clock_contrib:
            continue
        flow.append(Paragraph(f"{clock_name.upper()} CONTRIBUTIONS",
                                styles["h2"]))
        ranked = sorted(clock_contrib.items(),
                         key=lambda kv: abs(kv[1] or 0), reverse=True)
        c_rows = []
        c_statuses = []
        for marker, contrib in ranked:
            c = contrib or 0
            if c > 0.05:
                direction, status = "Accelerator", "red"
            elif c < -0.05:
                direction, status = "Decelerator", "green"
            else:
                direction, status = "Neutral", "neutral"
            c_rows.append([
                f"<b>{marker}</b>",
                f"{c:+.2f}",
                direction,
            ])
            c_statuses.append(status)
        flow.append(_status_lab_table(
            headers=["Marker", "Δ years", "Direction"],
            rows=c_rows,
            statuses=c_statuses,
            value_col_idx=1,
            status_col_idx=2,
            col_widths=[USABLE_W * 0.40, USABLE_W * 0.20, USABLE_W * 0.40],
            styles=styles,
        ))

    # ----- Intervention targets -----
    flow.append(PageBreak())
    flow.append(Paragraph(
        "Intervention Targets (ranked by predicted Δ-age impact)",
        styles["h1"],
    ))
    flow.append(Paragraph(
        "Each target lists a clinical priority, the rationale tied to "
        "biomarker contribution, the lifestyle / nutraceutical approach, "
        "and longevity-medicine pharmacologic options to consider for this "
        "specific patient profile. Off-label uses are noted; clinician "
        "judgment and shared decision-making apply.",
        styles["small"],
    ))
    targets = narrative.get("intervention_targets") or \
              _physician_static_targets(contributions)
    for i, t in enumerate(targets, start=1):
        if isinstance(t, str):
            target, rationale, approach, lrx = t, "", "", ""
        else:
            target    = t.get("target", "")
            rationale = t.get("rationale", "")
            approach  = t.get("approach", "")
            lrx       = t.get("longevity_rx", "")
        flow.append(Paragraph(
            f"<font color='#0D1B3E'><b>{i}.&nbsp;&nbsp;{target}</b></font>",
            styles["body"],
        ))
        if rationale:
            flow.append(Paragraph(
                f"<i>Rationale:</i> {rationale}", styles["small"]))
        if approach:
            flow.append(Paragraph(
                f"<b>Approach:</b> {approach}", styles["body"]))
        if lrx:
            flow.append(Paragraph(
                f"<b><font color='#C9941A'>Longevity Rx to consider:</font></b> "
                f"{lrx}",
                styles["body"],
            ))
        flow.append(Spacer(1, 0.08 * inch))

    # ----- Follow-up -----
    follow = narrative.get("follow_up")
    if follow:
        flow.append(Paragraph("Follow-Up", styles["h1"]))
        flow.append(Paragraph(follow, styles["body"]))

    # ----- Lab reference table -----
    flow.append(PageBreak())
    flow.append(Paragraph("Lab Values - Reference Table", styles["h1"]))
    flow.append(Paragraph(
        "Values tinted "
        "<font color='#155724'><b>green</b></font> are within typical range, "
        "<font color='#856404'><b>yellow</b></font> borderline, "
        "<font color='#721C24'><b>red</b></font> outside the typical range.",
        styles["small"],
    ))
    pat_sex = patient.get("sex", "Male")
    lab_rows = []
    statuses = []
    for key, meta in LAB_METADATA.items():
        val = labs.get(key)
        if val is None:
            continue
        try:
            val_f = float(val)
            val_str = f"{val_f:.2f}"
            status = _classify_lab(key, val_f, pat_sex)
        except (TypeError, ValueError):
            val_str = str(val)
            status = "neutral"
        lab_rows.append([
            f"<b>{meta['label']}</b>",
            val_str,
            meta["units"],
            meta["ref_range"],
        ])
        statuses.append(status)
    if lab_rows:
        flow.append(_status_lab_table(
            headers=["Marker", "Value", "Units", "Typical range"],
            rows=lab_rows,
            statuses=statuses,
            value_col_idx=1,
            col_widths=[USABLE_W * 0.32, USABLE_W * 0.18,
                          USABLE_W * 0.20, USABLE_W * 0.30],
            styles=styles,
        ))

    flow.extend(_disclaimer(
        "Generated by the INEXION Longevity Registry. Models: PhenoAge "
        "(Levine 2018); organ-clocks fit on NHANES + MIDUS within-cohort "
        "regression. Δ-age values are statistical estimates with measurement "
        "error; bootstrap CIs available in the Patient Analysis app.",
        styles,
    ))

    summary_str = (
        f"Physician Report  ·  Age {patient.get('age', 0)} "
        f"{patient.get('sex', '')}"
    )
    on_page = _make_on_page("Physician Report", summary_str)
    doc.build(flow, onFirstPage=on_page, onLaterPages=on_page)
    buf.seek(0)
    return buf.read()
